PROJECT_NAME: api-medpoint
PROJECT_ID: wstzgukmsgoymkqijhbo
DEPLOYMENT_TARGET: cloud

ACCESS_TOKEN: sbp_099203fd79e0c9be19c7d74324b9aec3ceb93801
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzdHpndWttc2dveW1rcWlqaGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1NDkyMDgsImV4cCI6MjA0OTEyNTIwOH0.6ZAggT_jcbiY0duP7gcJPjca2UYBn5pYpgqzq-X1qyQ
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzdHpndWttc2dveW1rcWlqaGJvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMzU0OTIwOCwiZXhwIjoyMDQ5MTI1MjA4fQ.juFi6S0wPg3ufwin3MveTL1ai-ymPfYkiV_1NksSRek

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_PUBLIC_URL: https://wstzgukmsgoymkqijhbo.supabase.co

SERVER_HOST: 127.0.01
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
